### ISSUE TITLE
Metroidnization

### ISSUE THREAD

**Issue by SilverRain8** [KhaosVoid/MDSaveEditor#2]
Hey there,

I was just curious about what the "Metroidnization" box does? My first thought was that it activated the effect from the end of the game where every enemy Samus touches immediately dies since activating the Metroid Suit from your editor doesn't seem to activate that effect. But that doesn't seem to be the case, so I just wondering what that box actually did. Thanks!

**Comment by KhaosVoid** [comment]
Metroidnization is just an added animation. Samus 'drains' the energy from a Chozo Warrior X upon defeat. Currently, it is not known what can enable the one hit kill for enemies.
